# Generated by Django 4.0.4 on 2022-06-12 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('ip', models.GenericIPAddressField(protocol='IPv4')),
                ('port', models.IntegerField()),
                ('user', models.CharField(blank=True, default='', max_length=100)),
                ('password', models.CharField(blank=True, default='', max_length=100)),
                ('suffix', models.CharField(blank=True, default='', max_length=100)),
            ],
        ),
    ]
