# Generated by Django 4.0.4 on 2022-06-12 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='codecs',
            field=models.CharField(choices=[('h264', 'h264'), ('h265', 'h265')], default='', max_length=5),
        ),
        migrations.AlterField(
            model_name='camera',
            name='name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='camera',
            name='suffix',
            field=models.CharField(default='', max_length=100),
        ),
    ]
