# Generated by Django 4.0.4 on 2022-06-12 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0002_camera_codecs_alter_camera_name_alter_camera_suffix'),
    ]

    operations = [
        migrations.RenameField(
            model_name='camera',
            old_name='codecs',
            new_name='codec',
        ),
    ]
