# Generated by Django 4.0.4 on 2022-06-01 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('ip', models.GenericIPAddressField(protocol='IPv4')),
                ('codec', models.CharField(choices=[('1', 'h264'), ('2', 'h265')], max_length=1)),
                ('user', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('substream', models.BooleanField(default=False)),
            ],
        ),
    ]
