# Generated by Django 4.0.4 on 2022-06-12 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_screen', '0007_rename_ender_camera_suffix'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Camera',
        ),
    ]
